# Generated by Django 4.0.5 on 2022-06-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_options_alter_contact_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('processing', 'processing'), ('resolved', 'resolved')], default='new', max_length=50),
        ),
    ]
